package osint

import (
	"bytes"
	"context"
	"fmt"
	"text/template"
	"time"

	"go.uber.org/zap"
)

// AbuseReportGenerator creates abuse reports for carriers
type AbuseReportGenerator struct {
	logger *zap.Logger
}

// NewAbuseReportGenerator creates a new abuse report generator
func NewAbuseReportGenerator(logger *zap.Logger) *AbuseReportGenerator {
	return &AbuseReportGenerator{
		logger: logger.Named("osint.abuse_report"),
	}
}

// AbuseReport contains the generated abuse report
type AbuseReport struct {
	Carrier       string        `json:"carrier"`
	To            string        `json:"to"` // email or URL
	Subject       string        `json:"subject"`
	Body          string        `json:"body"`
	Cluster       *Cluster      `json:"cluster"`
	GeneratedAt   time.Time     `json:"generated_at"`
	AutoGenerated bool          `json:"auto_generated"`
}

// GenerateReport creates an abuse report for a scam cluster
func (g *AbuseReportGenerator) GenerateReport(ctx context.Context, cluster *Cluster) (*AbuseReport, error) {
	if cluster.AbuseContact == nil {
		return nil, fmt.Errorf("no abuse contact for carrier: %s", cluster.Carrier)
	}

	// Select template based on carrier
	tmpl, err := g.getTemplate(cluster.Carrier)
	if err != nil {
		return nil, fmt.Errorf("failed to get template: %w", err)
	}

	// Build template data
	data := struct {
		Cluster       *Cluster
		ReportDate    string
		ReportID      string
		ContactInfo   string
	}{
		Cluster:     cluster,
		ReportDate:  time.Now().Format("2006-01-02 15:04:05 MST"),
		ReportID:    cluster.ID,
		ContactInfo: "SafeRing Anti-Scam Platform (https://safering.deathbyathousand.com)",
	}

	var body bytes.Buffer
	if err := tmpl.Execute(&body, data); err != nil {
		return nil, fmt.Errorf("failed to execute template: %w", err)
	}

	report := &AbuseReport{
		Carrier:       cluster.Carrier,
		To:            cluster.AbuseContact.Email,
		Subject:       fmt.Sprintf("Abuse Report: %s Scam Campaign (Cluster %s)", cluster.ScamType, cluster.ID[:8]),
		Body:          body.String(),
		Cluster:       cluster,
		GeneratedAt:   time.Now(),
		AutoGenerated: cluster.AutoReport,
	}

	g.logger.Info("abuse report generated",
		zap.String("cluster_id", cluster.ID),
		zap.String("carrier", cluster.Carrier),
		zap.Int("numbers", len(cluster.Numbers)),
		zap.Bool("auto_generated", report.AutoGenerated))

	return report, nil
}

// getTemplate returns the appropriate template for a carrier
func (g *AbuseReportGenerator) getTemplate(carrier string) (*template.Template, error) {
	// Generic template works for most carriers
	// Can be customized per-carrier if needed
	tmplStr := `SafeRing Abuse Report
Report ID: {{.ReportID}}
Generated: {{.ReportDate}}
Reporter: {{.ContactInfo}}

SCAM CAMPAIGN SUMMARY
=====================
Scam Type: {{.Cluster.ScamType}}
Carrier: {{.Cluster.Carrier}} ({{.Cluster.CarrierType}})
NXX Prefix: {{.Cluster.NXXPrefix}}
Numbers Detected: {{len .Cluster.Numbers}}
Confidence Score: {{printf "%.2f" .Cluster.Confidence}}
Detection Window: Last 72 hours

EVIDENCE
========
The following phone numbers have been reported as part of a coordinated {{.Cluster.ScamType}} scam campaign:

{{range .Cluster.Numbers}}
- {{.PhoneNumber}}
  Hash: {{.Hash}}
  Risk Score: {{printf "%.2f" .RiskScore}}
  Reported: {{.ReportedAt.Format "2006-01-02 15:04:05 MST"}}
  Caller Name: {{.CallerName}}
{{end}}

ANALYSIS
========
These numbers share the following characteristics:
- Same NXX prefix ({{.Cluster.NXXPrefix}}), indicating same area code + exchange
- Same scam type: {{.Cluster.ScamType}}
- Reported within 72-hour window
- {{if eq .Cluster.CarrierType "voip"}}VOIP numbers (commonly used for scams){{else}}{{.Cluster.CarrierType}} numbers{{end}}
- Registered with {{.Cluster.Carrier}}

IMPACT
======
These numbers are being used to target victims with {{.Cluster.ScamType}} scams.
Immediate action is requested to prevent further abuse.

REQUESTED ACTIONS
=================
1. Investigate the account(s) associated with these numbers
2. Suspend accounts found to be engaged in fraudulent activity
3. Provide confirmation of action taken

If you need additional information or evidence, please contact us at the email above.

Thank you for your prompt attention to this matter.

---
This report was {{if .AutoGenerated}}automatically generated{{else}}manually generated{{end}} by the SafeRing platform.
SafeRing is a community-driven anti-scam initiative protecting vulnerable users from phone-based fraud.
`

	return template.New("abuse_report").Parse(tmplStr)
}

// SendReport sends the abuse report to the carrier
// For now, this just logs it. In production, you'd integrate with email/HTTP APIs.
func (g *AbuseReportGenerator) SendReport(ctx context.Context, report *AbuseReport) error {
	// TODO: Implement actual sending
	// Options:
	// 1. SMTP for email-based reporting
	// 2. HTTP POST for carriers with web forms
	// 3. Carrier-specific APIs (Twilio has abuse reporting API)

	g.logger.Info("abuse report would be sent",
		zap.String("carrier", report.Carrier),
		zap.String("to", report.To),
		zap.String("subject", report.Subject),
		zap.Bool("auto_generated", report.AutoGenerated))

	// For now, just log it
	fmt.Println("\n" + "=" + string(make([]byte, 70)) + "=")
	fmt.Println(report.Subject)
	fmt.Println("To:", report.To)
	fmt.Println("=" + string(make([]byte, 70)) + "=")
	fmt.Println(report.Body)
	fmt.Println("=" + string(make([]byte, 70)) + "=" + "\n")

	return nil
}
